"""api_url added

Revision ID: 03dc84d852f2
Revises: 9a6655ea987f
Create Date: 2025-02-08 20:09:07.818501

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03dc84d852f2'
down_revision = '9a6655ea987f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('voip_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('api_url', sa.String(length=255), nullable=False))
        batch_op.alter_column('api_did',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('voip_settings', schema=None) as batch_op:
        batch_op.alter_column('api_did',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('api_url')

    # ### end Alembic commands ###
