"""Add payment_due_date and notifications to User model

Revision ID: 080459ba0a3a
Revises: e55c3191290a
Create Date: 2025-01-29 17:09:05.935993

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '080459ba0a3a'
down_revision = 'e55c3191290a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notifications', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('payment_due_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('payment_due_date')
        batch_op.drop_column('notifications')

    # ### end Alembic commands ###
