"""phone_verification_token columns added

Revision ID: 27c71352296b
Revises: e812cf66baf4
Create Date: 2025-02-25 19:53:30.325512

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27c71352296b'
down_revision = 'e812cf66baf4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone_verified', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('phone_verification_token', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('phone_verification_token')
        batch_op.drop_column('phone_verified')

    # ### end Alembic commands ###
