"""is_paid col added to user table

Revision ID: 3f1df1f6dd0f
Revises: c9beb8672f23
Create Date: 2025-01-29 02:39:58.322226

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f1df1f6dd0f'
down_revision = 'c9beb8672f23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_paid', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_paid')

    # ### end Alembic commands ###
