"""Initial migration with named constraints

Revision ID: 815996111b82
Revises: 
Create Date: 2025-01-25 14:31:51.645731

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '815996111b82'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amazon_relay_email', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('amazon_relay_password', sa.String(length=60), nullable=True))
        batch_op.create_unique_constraint('uq_user_username', ['username'])
        batch_op.create_unique_constraint('uq_user_amazon_relay_email', ['amazon_relay_email'])    

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('amazon_relay_password')
        batch_op.drop_column('amazon_relay_email')

    # ### end Alembic commands ###
