"""Add SMTP settings table

Revision ID: 85483b8e3913
Revises: ac622f9c1c90
Create Date: 2025-02-06 00:58:59.137530

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85483b8e3913'
down_revision = 'ac622f9c1c90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('smtp_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('smtp_server', sa.String(length=255), nullable=False),
    sa.Column('smtp_port', sa.Integer(), nullable=False),
    sa.Column('smtp_username', sa.String(length=255), nullable=False),
    sa.Column('smtp_password', sa.String(length=255), nullable=False),
    sa.Column('smtp_use_tls', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('smtp_settings')
    # ### end Alembic commands ###
