"""Add email verification fields

Revision ID: 96958a0d7ebf
Revises: 9ff58992c045
Create Date: 2025-02-02 00:41:18.322658

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96958a0d7ebf'
down_revision = '9ff58992c045'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_verified', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('verification_token', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('verification_token')
        batch_op.drop_column('email_verified')

    # ### end Alembic commands ###
