"""api_did added on voipmssetting

Revision ID: 9a6655ea987f
Revises: 85483b8e3913
Create Date: 2025-02-08 19:53:28.878283

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a6655ea987f'
down_revision = '85483b8e3913'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('payment')
    with op.batch_alter_table('voip_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('api_did', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('voip_settings', schema=None) as batch_op:
        batch_op.drop_column('api_did')

    op.create_table('payment',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('amount', sa.FLOAT(), nullable=False),
    sa.Column('date', sa.DATETIME(), nullable=True),
    sa.Column('payment_method', sa.VARCHAR(length=20), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
