"""Add SMS opt-in and fee tracking

Revision ID: 9ff58992c045
Revises: 0bfeb2ba0dc4
Create Date: 2025-01-31 22:09:51.191624

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ff58992c045'
down_revision = '0bfeb2ba0dc4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sms_opt_in', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('sms_fee_due', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('sms_fee_due')
        batch_op.drop_column('sms_opt_in')

    # ### end Alembic commands ###
