"""push and email enabled colmn added

Revision ID: ad1682b38a2f
Revises: 27c71352296b
Create Date: 2025-03-04 01:05:31.294038

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad1682b38a2f'
down_revision = '27c71352296b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_enabled', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('push_enabled', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('push_enabled')
        batch_op.drop_column('email_enabled')

    # ### end Alembic commands ###
