"""VoipSettings table

Revision ID: bcd63aaaa760
Revises: d646b4c1e4db
Create Date: 2025-02-05 10:58:03.339165

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bcd63aaaa760'
down_revision = 'd646b4c1e4db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('voip_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('api_username', sa.String(length=255), nullable=False),
    sa.Column('api_password', sa.String(length=255), nullable=False),
    sa.Column('sms_enabled', sa.Boolean(), nullable=True),
    sa.Column('sms_fee', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('voip_settings')
    # ### end Alembic commands ###
