"""add ssl and DEFAULT_SENDER on smtp setting

Revision ID: bf6e0d4eee88
Revises: 03dc84d852f2
Create Date: 2025-02-08 23:07:13.079393

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf6e0d4eee88'
down_revision = '03dc84d852f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('smtp_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('smtp_use_ssl', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('default_sender', sa.String(length=255), nullable=True))

    with op.batch_alter_table('voip_settings', schema=None) as batch_op:
        batch_op.alter_column('api_did',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('voip_settings', schema=None) as batch_op:
        batch_op.alter_column('api_did',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('smtp_settings', schema=None) as batch_op:
        batch_op.drop_column('default_sender')
        batch_op.drop_column('smtp_use_ssl')

    # ### end Alembic commands ###
