"""recreate migration

Revision ID: c9beb8672f23
Revises: 
Create Date: 2025-01-29 01:58:08.408217

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9beb8672f23'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uq_user_username', sa.String(length=20), nullable=False),
    sa.Column('uq_user_email', sa.String(length=120), nullable=False),
    sa.Column('uq_user_phone_number', sa.String(length=15), nullable=True),
    sa.Column('password', sa.String(length=60), nullable=False),
    sa.Column('role', sa.String(length=10), nullable=False),
    sa.Column('uq_user_amazon_relay_email', sa.String(length=120), nullable=True),
    sa.Column('amazon_relay_password', sa.String(length=60), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uq_user_amazon_relay_email'),
    sa.UniqueConstraint('uq_user_email'),
    sa.UniqueConstraint('uq_user_phone_number'),
    sa.UniqueConstraint('uq_user_username')
    )
    op.create_table('payment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('payment_method', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payment')
    op.drop_table('user')
    # ### end Alembic commands ###
