"""Create RelayData table

Revision ID: dc0b54f39bc2
Revises: ad1682b38a2f
Create Date: 2025-03-06 01:49:52.851257

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc0b54f39bc2'
down_revision = 'ad1682b38a2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('relay_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.String(length=120), nullable=True),
    sa.Column('load_id', sa.String(length=120), nullable=True),
    sa.Column('from_to', sa.String(length=120), nullable=True),
    sa.Column('driver_name', sa.String(length=120), nullable=True),
    sa.Column('loadType', sa.String(length=120), nullable=True),
    sa.Column('createTime', sa.String(length=120), nullable=True),
    sa.Column('status', sa.String(length=120), nullable=True),
    sa.Column('planned_arrival_stop1', sa.String(length=120), nullable=True),
    sa.Column('actual_arrival_stop1', sa.String(length=120), nullable=True),
    sa.Column('planned_Departure_stop1', sa.String(length=120), nullable=True),
    sa.Column('actual_Departure_stop1', sa.String(length=120), nullable=True),
    sa.Column('planned_arrival_stop2', sa.String(length=120), nullable=True),
    sa.Column('actual_arrival_stop2', sa.String(length=120), nullable=True),
    sa.Column('planned_Departure_stop2', sa.String(length=120), nullable=True),
    sa.Column('actual_Departure_stop2', sa.String(length=120), nullable=True),
    sa.Column('actual_stats', sa.String(length=120), nullable=True),
    sa.Column('arrival_departure_time', sa.String(length=120), nullable=True),
    sa.Column('tabname', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('relay_data')
    # ### end Alembic commands ###
